### ISSUE TITLE
classify() method does not return correct distribution

### ISSUE THREAD

**Issue by timjzee** [proycon/python-timbl#4]
I'm using the LaMachine virtual environment on Ponyland

`classifier = timbl.TimblClassifier("pl_type.master", "-mO:I1 -k 5 -G 0")`

Should return probability distribution that adds up to 1, but ...

`classifier.classify(("administrateur", "n", "i", "=", "str", "a", "=", "t", "|", "r", "-", "-", "+", "r"))`

returns:

`{'EN': 1, 'S': 1}`

But the same classifier returns the correct distribution if the `test()` method is used instead:

`{ EN 0.0526316, S 0.947368 }`

**Comment by proycon** [comment]
The ``classify()`` only returns a class distribution only when you instantiate the TimblClassifier with the keyword argument ``dist=True``, by default it doesn't do that indeed (because it takes some extra computation), similarly you can also decide whether to normalize the distribution (``normalize=True`` (default)) or not.

**Comment by timjzee** [comment]
Thanks for responding! That still doesn't work for me though. Let's take the Readme example:

`classifier = timbl.TimblClassifier("test-norm", "-a 0 -k 5 -G 0", dist=True, normalize=True)`
`classifier.append( (1,0,0), 'financial')`
`classifier.append( (0,1,0), 'furniture')`
`classifier.append( (0,0,1), 'geographic')`
`classifier.train()`
`classifier.classify( (1,0,0) )`

Still returns:

`('financial', {'financial': 1, 'furniture': 1, 'geographic': 1}, 0.0)`

**Comment by proycon** [comment]
Hmm... that might be a bug after all then.. Could you try setting the timbl options ``+v+db +v+di`` explicitly and see if that makes a difference?

**Comment by timjzee** [comment]
That isn't it either. The training procedure actually shows that those options are added twice now (because it automatically adds them):

`Calling Timbl API for training: -F Tabbed -a 0 -k 5 -G 0 +v+db +v+di +v+db +v+di`

**Comment by proycon** [comment]
I'll do some extra debugging to see what's going on, I'm not sure either at this stage, it's been a while since I've looked at it. Let's hope we can solve it without dragging main developer @kosloot from his retirement ;)

**Comment by timjzee** [comment]
Haha, fingers crossed. As the test() method works perfectly fine, I don't actually need classify(). It would just be more convenient. Thanks for taking a look!

**Comment by kosloot** [comment]
awaking from retirement coma...
checking normalization code in https://github.com/proycon/python-timbl/blob/master/src/timblapi.cc
line 248. 
this is dead wrong imho.
so retiring again

**Comment by proycon** [comment]
Indeed, that code looks very weird... I hope I didn't write it but I fear I might have... :$ Will investigate further...

**Comment by proycon** [comment]
I fixed the problem and released v2020.05.09. It's deployed it in LaMachine on ponyland as well. Can you give it a try to see if everything now works as expected? Neither the ``dist`` argument I mentioned previously nor the explicit ``+v+db +v+di`` options should be necessary anymore.

**Comment by timjzee** [comment]
I tested it with the Readme example and my own larger dataset. It works! Thanks for fixing!
