### ISSUE TITLE
Installation fails on an ARM64 Macbook Pro

### ISSUE THREAD

**Issue by antalvdb** [proycon/python-timbl#5]
Installation fails on an ARM64 Macbook Pro. boost-python3 is installed through brew. timbl is installed in /usr/local.

```
(ml) python-timbl % sudo python3 setup.py build_ext --boost-include-dir=/opt/homebrew/include/ --boost-library-dir=/opt/homebrew/lib --timbl-include-dir=/usr/local/include --timbl-library-dir=/usr/local/lib install
/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/dist.py:530: UserWarning: Normalizing '2020.06.08' to '2020.6.8'
  warnings.warn(tmpl.format(**locals()))
running build_ext
Unable to find boost library directory automatically. Is libboost-python3 installed? Set --boost-library-dir?
Unable to find boost headers automatically. Is libboost-python-dev installed? Set --boost-include-dir
Traceback (most recent call last):
  File "/Users/bosch075/Software/python-timbl/setup.py", line 197, in <module>
    setup(
  File "/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.ensure_finalized()
  File "/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/Users/bosch075/Software/python-timbl/setup.py", line 155, in finalize_options
    self.ensure_file_exists("libxml2_include_dir", "libxml/tree.h")
  File "/Users/bosch075/Software/python-timbl/setup.py", line 159, in ensure_file_exists
    self.ensure_dirname(option)
  File "/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 263, in ensure_dirname
    self._ensure_tested_string(
  File "/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 250, in _ensure_tested_string
    val = self._ensure_stringlike(option, what, default)
  File "/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/__init__.py", line 162, in _ensure_stringlike
    val = getattr(self, option)
  File "/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
    raise AttributeError(attr)
AttributeError: libxml2_include_dir. Did you mean: 'timbl_include_dir'?
```

**Comment by proycon** [comment]
Further compilation problems are also present on a modern Linux system:

```
$ pip install python3-timbl
Collecting python3-timbl
  Downloading python3-timbl-2020.06.08.tar.gz (29 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: python3-timbl
  Building wheel for python3-timbl (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for python3-timbl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      <string>:11: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
      /tmp/pip-build-env-9gzrdogn/overlay/lib/python3.12/site-packages/setuptools/dist.py:333: InformationOnly: Normalizing '2020.06.08' to '2020.6.8'
        self.metadata.version = self._normalize_version(self.metadata.version)
      Detected boost library in /usr/lib (boost_python3)
      Detected boost headers in /usr/include
      In file included from /usr/include/unicode/unistr.h:39,
                       from /usr/include/timbl/StringOps.h:37,
                       from /usr/include/timbl/Types.h:42,
                       from /usr/include/timbl/TimblAPI.h:36,
                       from src/timblapi.h:51,
                       from src/timblapi.cc:47:
      /usr/include/unicode/stringpiece.h:133:29: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
        133 |             typename = std::enable_if_t<
            |                             ^~~~~~~~~~~
      /usr/include/unicode/stringpiece.h:133:24: note: ‘std::enable_if_t’ is only available from C++14 onwards
        133 |             typename = std::enable_if_t<
            |                        ^~~
      /usr/include/unicode/stringpiece.h:133:40: error: expected ‘>’ before ‘<’ token
        133 |             typename = std::enable_if_t<
            |                                        ^
      In file included from /usr/include/unicode/uenum.h:25,
                       from /usr/include/unicode/utrans.h:22,
                       from /usr/include/unicode/translit.h:29,
                       from /usr/include/ticcutils/Unicode.h:40,
                       from /usr/include/timbl/Instance.h:31,
                       from /usr/include/timbl/TimblAPI.h:37:
      /usr/include/unicode/localpointer.h:561:26: error: parameter declared ‘auto’
        561 | template <typename Type, auto closeFunction>
            |                          ^~~~
      /usr/include/unicode/localpointer.h:573:76: error: template argument 2 is invalid
        573 |     explicit LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
            |                                                                            ^
      /usr/include/unicode/localpointer.h:583:78: error: template argument 2 is invalid
        583 |     LocalOpenPointer &operator=(std::unique_ptr<Type, decltype(closeFunction)> &&p) {
            |                                                                              ^
      /usr/include/unicode/localpointer.h:599:59: error: template argument 2 is invalid
        599 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
            |                                                           ^
      /usr/include/unicode/uenum.h:69:1: note: invalid template non-type parameter
         69 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUEnumerationPointer, UEnumeration, uenum_close);
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/unicode/uset.h:358:1: note: invalid template non-type parameter
        358 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUSetPointer, USet, uset_close);
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/unicode/utrans.h:258:1: note: invalid template non-type parameter
        258 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUTransliteratorPointer, UTransliterator, utrans_close);
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/unicode/unorm2.h:286:1: note: invalid template non-type parameter
        286 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUNormalizer2Pointer, UNormalizer2, unorm2_close);
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/unicode/utext.h:1596:1: note: invalid template non-type parameter
       1596 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUTextPointer, UText, utext_close);
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/unicode/uregex.h:229:1: note: invalid template non-type parameter
        229 | U_DEFINE_LOCAL_OPEN_POINTER(LocalURegularExpressionPointer, URegularExpression, uregex_close);
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/timblapi.cc: In member function ‘boost::python::tuple TimblApiWrapper::classify3safe(const std::string&, bool, unsigned char)’:
      src/timblapi.cc:146:60: error: no matching function for call to ‘Timbl::TimblExperiment::Classify(const std::string&, const Timbl::ValueDistribution*&, double&)’
        146 |     const Timbl::TargetValue * result = clonedexp->Classify(line, distrib,distance);
            |                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /usr/include/timbl/TimblAPI.h:39:
      /usr/include/timbl/TimblExperiment.h:192:10: note: candidate: ‘bool Timbl::TimblExperiment::Classify(const std::string&, std::string&, std::string&, double&)’
        192 |     bool Classify( const std::string& , std::string&, std::string&, double& );
            |          ^~~~~~~~
      /usr/include/timbl/TimblExperiment.h:192:10: note:   candidate expects 4 arguments, 3 provided
      /usr/include/timbl/TimblExperiment.h:193:10: note: candidate: ‘bool Timbl::TimblExperiment::Classify(const icu_75::UnicodeString&, icu_75::UnicodeString&)’
        193 |     bool Classify( const icu::UnicodeString& , icu::UnicodeString& );
            |          ^~~~~~~~
      /usr/include/timbl/TimblExperiment.h:193:10: note:   candidate expects 2 arguments, 3 provided
      /usr/include/timbl/TimblExperiment.h:194:10: note: candidate: ‘bool Timbl::TimblExperiment::Classify(const icu_75::UnicodeString&, icu_75::UnicodeString&, icu_75::UnicodeString&, double&)’
        194 |     bool Classify( const icu::UnicodeString&,
            |          ^~~~~~~~
      /usr/include/timbl/TimblExperiment.h:194:10: note:   candidate expects 4 arguments, 3 provided
      /usr/include/timbl/TimblExperiment.h:206:24: note: candidate: ‘const Timbl::TargetValue* Timbl::TimblExperiment::Classify(const icu_75::UnicodeString&, const Timbl::ClassDistribution*&, double&)’
        206 |     const TargetValue *Classify( const icu::UnicodeString& Line,
            |                        ^~~~~~~~
      /usr/include/timbl/TimblExperiment.h:206:60: note:   no known conversion for argument 1 from ‘const std::string’ {aka ‘const std::__cxx11::basic_string<char>’} to ‘const icu_75::UnicodeString&’
        206 |     const TargetValue *Classify( const icu::UnicodeString& Line,
            |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
      /usr/include/timbl/TimblExperiment.h:216:24: note: candidate: ‘const Timbl::TargetValue* Timbl::TimblExperiment::Classify(const icu_75::UnicodeString&)’
        216 |     const TargetValue *Classify( const icu::UnicodeString& Line ){
            |                        ^~~~~~~~
      /usr/include/timbl/TimblExperiment.h:216:24: note:   candidate expects 1 argument, 3 provided
      /usr/include/timbl/TimblExperiment.h:221:24: note: candidate: ‘const Timbl::TargetValue* Timbl::TimblExperiment::Classify(const icu_75::UnicodeString&, const Timbl::ClassDistribution*&)’
        221 |     const TargetValue *Classify( const icu::UnicodeString& Line,
            |                        ^~~~~~~~
      /usr/include/timbl/TimblExperiment.h:221:24: note:   candidate expects 2 arguments, 3 provided
      /usr/include/timbl/TimblExperiment.h:232:24: note: candidate: ‘const Timbl::TargetValue* Timbl::TimblExperiment::Classify(const icu_75::UnicodeString&, double&)’
        232 |     const TargetValue *Classify( const icu::UnicodeString& Line,
            |                        ^~~~~~~~
      /usr/include/timbl/TimblExperiment.h:232:24: note:   candidate expects 2 arguments, 3 provided
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python3-timbl
Failed to build python3-timbl
```

**Comment by proycon** [comment]
I'm still having trouble building wheels for mac. I did update the code against the latest Timbl API now. Could you try build the latest git version on a mac?

**Comment by antalvdb** [comment]
Using the setup.py install option:

python-timbl % sudo python3 setup.py build_ext --boost-include-dir=/opt/homebrew/include --boost-library-dir=/opt/homebrew/lib --timbl-include-dir=/usr/local/include --timbl-library-dir=/usr/local/lib install
system=Darwin machine=arm64
(macos arm64 detected)
include_dirs=/opt/homebrew/include /opt/homebrew/icu4c/include /opt/homebrew/libxml2/include /opt/homebrew/libxml2/include/libxml2 /opt/homebrew/opt/icu4c/include /opt/homebrew/opt/libxml2/include /opt/homebrew/opt/boost-python3/include /opt/homebrew/opt/boost/include /usr/include/ /usr/include/libxml2 /usr/local/include/ library_dirs=/opt/homebrew/lib /opt/homebrew/icu4c/lib /opt/homebrew/libxml2/lib /opt/homebrew/opt/icu4c/lib /opt/homebrew/opt/libxml2/lib /opt/homebrew/opt/boost-python3/lib /opt/homebrew/opt/boost/lib /usr/lib /usr/local/lib extra_options=--stdlib=libc++ -D U_USING_ICU_NAMESPACE=1
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --boost-include-dir not recognized

**Comment by proycon** [comment]
Try without all the options, just `sudo python3 setup.py install`, I removed them and rely on autodetection mostly.

**Comment by antalvdb** [comment]
python-timbl % sudo python3 setup.py install
system=Darwin machine=arm64
(macos arm64 detected)
include_dirs=/opt/homebrew/include /opt/homebrew/icu4c/include /opt/homebrew/libxml2/include /opt/homebrew/libxml2/include/libxml2 /opt/homebrew/opt/icu4c/include /opt/homebrew/opt/libxml2/include /opt/homebrew/opt/boost-python3/include /opt/homebrew/opt/boost/include /usr/include/ /usr/include/libxml2 /usr/local/include/ library_dirs=/opt/homebrew/lib /opt/homebrew/icu4c/lib /opt/homebrew/libxml2/lib /opt/homebrew/opt/icu4c/lib /opt/homebrew/opt/libxml2/lib /opt/homebrew/opt/boost-python3/lib /opt/homebrew/opt/boost/lib /usr/lib /usr/local/lib extra_options=--stdlib=libc++ -D U_USING_ICU_NAMESPACE=1
running install
/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/miniconda3/envs/ml/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing python3_timbl.egg-info/PKG-INFO
writing dependency_links to python3_timbl.egg-info/dependency_links.txt
writing top-level names to python3_timbl.egg-info/top_level.txt
Unable to find boost library directory automatically. Is libboost-python3 installed? Set --boost-library-dir?
Detected boost headers in /opt/homebrew/include
reading manifest file 'python3_timbl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'COPYING'
writing manifest file 'python3_timbl.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-11.1-arm64/egg
running install_lib
running build_py
running build_ext
building 'timblapi' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/miniconda3/envs/ml/include -arch arm64 -fPIC -O2 -isystem /opt/miniconda3/envs/ml/include -arch arm64 -I/opt/homebrew/include -I/opt/homebrew/icu4c/include -I/opt/homebrew/libxml2/include -I/opt/homebrew/libxml2/include/libxml2 -I/opt/homebrew/opt/icu4c/include -I/opt/homebrew/opt/libxml2/include -I/opt/homebrew/opt/boost-python3/include -I/opt/homebrew/opt/boost/include -I/usr/include/ -I/usr/include/libxml2 -I/usr/local/include/ -I/opt/miniconda3/envs/ml/include/python3.10 -c src/timblapi.cc -o build/temp.macosx-11.1-arm64-cpython-310/src/timblapi.o -std=c++17 -stdlib=libc++
clang++ -bundle -undefined dynamic_lookup -Wl,-rpath,/opt/miniconda3/envs/ml/lib -L/opt/miniconda3/envs/ml/lib -Wl,-rpath,/opt/miniconda3/envs/ml/lib -L/opt/miniconda3/envs/ml/lib build/temp.macosx-11.1-arm64-cpython-310/src/timblapi.o -L/opt/homebrew/lib -L/opt/homebrew/icu4c/lib -L/opt/homebrew/libxml2/lib -L/opt/homebrew/opt/icu4c/lib -L/opt/homebrew/opt/libxml2/lib -L/opt/homebrew/opt/boost-python3/lib -L/opt/homebrew/opt/boost/lib -L/usr/lib -L/usr/local/lib -ltimbl -lboost_python -o build/lib.macosx-11.1-arm64-cpython-310/timblapi.cpython-310-darwin.so
ld: warning: duplicate -rpath '/opt/miniconda3/envs/ml/lib' ignored
ld: warning: search path '/opt/homebrew/icu4c/lib' not found
ld: warning: search path '/opt/homebrew/libxml2/lib' not found
ld: library 'boost_python' not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit code 1

**Comment by proycon** [comment]
Is boost-python3 installed through homebrew? `brew install boost-python3`

**Comment by antalvdb** [comment]
Yes.

**Comment by proycon** [comment]
Hmm, where is it on disk? Do you have a `/opt/homebrew/boost-python3` ? Could you send `ls -R` output from that dir? Perhaps I'm looking in the wrong place (I have no mac to try).

**Comment by antalvdb** [comment]
There is

/opt/homebrew/opt/boost-python3
/opt/homebrew/var/homebrew/linked/boost-python3

% cd /opt/homebrew/opt/boost-python3
% ls -R
INSTALL_RECEIPT.json	lib
README.md		sbom.spdx.json

./lib:
cmake				libboost_python312-mt.a
libboost_numpy312-mt.a		libboost_python312-mt.dylib
libboost_numpy312-mt.dylib	libboost_python312.a
libboost_numpy312.a		libboost_python312.dylib
libboost_numpy312.dylib

./lib/cmake:
boost_numpy-1.86.0	boost_python-1.86.0

./lib/cmake/boost_numpy-1.86.0:
boost_numpy-config-version.cmake
boost_numpy-config.cmake
libboost_numpy-variant-mt-shared-py3.12.cmake
libboost_numpy-variant-mt-static-py3.12.cmake
libboost_numpy-variant-shared-py3.12.cmake
libboost_numpy-variant-static-py3.12.cmake

./lib/cmake/boost_python-1.86.0:
boost_python-config-version.cmake
boost_python-config.cmake
libboost_python-variant-mt-shared-py3.12.cmake
libboost_python-variant-mt-static-py3.12.cmake
libboost_python-variant-shared-py3.12.cmake
libboost_python-variant-static-py3.12.cmake

**Comment by proycon** [comment]
Ha, I think I see what I missed, can you git pull and try again?

**Comment by antalvdb** [comment]
Looks like the same error:

...
ld: warning: duplicate -rpath '/opt/miniconda3/envs/ml/lib' ignored
ld: warning: search path '/opt/homebrew/icu4c/lib' not found
ld: warning: search path '/opt/homebrew/libxml2/lib' not found
ld: library 'boost_python3' not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit code 1

**Comment by proycon** [comment]
Hmm, I assume it still also says "Unable to find boost library directory automatically." then?

**Comment by proycon** [comment]
Ah! Are you running on Python 3.10 or 3.12? There seems to be a mismatch here. The boost-python library is installed for Python 3.12 only, and you're conda seems to be doing 3.10. That might be why it can't find it! Try create a new conda environment with 3.12.

**Comment by antalvdb** [comment]
Yes, that works. Thanks! Example.py runs successfully.

Installation still drops various warnings:

% sudo python3 setup.py install
/Users/bosch075/Software/python-timbl/setup.py:11: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer
system=Darwin machine=arm64
(macos arm64 detected)
include_dirs=/opt/homebrew/include /opt/homebrew/icu4c/include /opt/homebrew/libxml2/include /opt/homebrew/libxml2/include/libxml2 /opt/homebrew/opt/icu4c/include /opt/homebrew/opt/libxml2/include /opt/homebrew/opt/boost/include /usr/include/ /usr/include/libxml2 /usr/local/include/ library_dirs=/opt/homebrew/lib /opt/homebrew/icu4c/lib /opt/homebrew/libxml2/lib /opt/homebrew/opt/icu4c/lib /opt/homebrew/opt/libxml2/lib /opt/homebrew/opt/boost-python3/lib /opt/homebrew/opt/boost/lib /usr/lib /usr/local/lib extra_options=--stdlib=libc++ -D U_USING_ICU_NAMESPACE=1
/opt/miniconda3/envs/ml3.12/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/opt/miniconda3/envs/ml3.12/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
Detected boost library in /opt/homebrew/opt/boost-python3/lib (boost_python312)
Detected boost headers in /opt/homebrew/opt/boost/include
ld: warning: duplicate -rpath '/opt/miniconda3/envs/ml3.12/lib' ignored
ld: warning: search path '/opt/homebrew/icu4c/lib' not found
ld: warning: search path '/opt/homebrew/libxml2/lib' not found
zip_safe flag not set; analyzing archive contents...
__pycache__.timblapi.cpython-312: module references __file__

**Comment by proycon** [comment]
Glad to see it finally works! 

There are some more deprecated components which I should clean up yes. If we want to distribute things properly serious with it we really need Python wheels, but I'm stuck a bit there on mac. Then again, python-timbl had been broken since 2022 and nobody noticed until you picked it up now, so I doubt there's much wider interest ;)

**Comment by antalvdb** [comment]
Thanks for the fix anyway!
